-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABDU3T+2Hk
Vly0XjIQUYsEf4AAAAGAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIIIVG/xUNaHn1ha6
rFCVFJdsCTliGAtKr/Prz92pRdtuAAAAoOiI7aE6AA3Yq9i3acfuZDz2mIfJE3J+WmqHH4
WDDjs+j81mp+GsO6XXfPrBMUurCUg1VM+ccGTzen4UZhm7yMHvQDzyBCMa3ZKvsEGCTGhA
8B+RDP2wrtYtiyn/YUC8F8XyhKtCHiiBEf2sDBU+6pKtoxIWPJUricVJrW7zkAgAOsVuJZ
aKXpSWUZdLDACn3RCEwv77KRQfCHI+8o+onDU=
-----END OPENSSH PRIVATE KEY-----
